export const orders = [
  {
    id: 1,
    orderCreatedAt: '2024-06-30',
    orderMemberId: 'hong111',
    totalOrderPrice: 30000,
    orderPaymentMethod: 'CARD',
    orderStatus: 'APPROVED',
    orderOption: 'SINGLE',
  },
  {
    id: 2,
    orderCreatedAt: '2024-07-01',
    orderMemberId: 'hong222',
    totalOrderPrice: 30001,
    orderPaymentMethod: 'CARD',
    orderStatus: 'MODIFIED',
    orderOption: 'SUBSCRIPTION',
  },
  {
    id: 3,
    orderCreatedAt: '2024-07-02',
    orderMemberId: 'hong333',
    totalOrderPrice: 30002,
    orderPaymentMethod: 'ACCOUNT',
    orderStatus: 'DENIED',
    orderOption: 'SINGLE',
  },
  {
    id: 4,
    orderCreatedAt: '2024-07-03',
    orderMemberId: 'hong444',
    totalOrderPrice: 30003,
    orderPaymentMethod: 'CARD',
    orderStatus: 'APPROVED',
    orderOption: 'SINGLE',
  },
  {
    id: 5,
    orderCreatedAt: '2024-07-04',
    orderMemberId: 'hong555',
    totalOrderPrice: 30004,
    orderPaymentMethod: 'CARD',
    orderStatus: 'MODIFIED',
    orderOption: 'SUBSCRIPTION',
  },
  {
    id: 6,
    orderCreatedAt: '2024-07-05',
    orderMemberId: 'hong6666',
    totalOrderPrice: 30005,
    orderPaymentMethod: 'ACCOUNT',
    orderStatus: 'DENIED',
    orderOption: 'SUBSCRIPTION',
  },
];
