export const users = [
  {
    id: 1,
    memberEmail: 'neil.sims@flowbite.com',
    memberName: 'Neil Sims',
    memberPhone: '123-456-7890',
    memberRegisterDate: '2022-01-15',
    memberRegisterStatus: true,
  },
  {
    id: 2,
    memberEmail: 'jane.doe@flowbite.com',
    memberName: 'Jane Doe',
    memberPhone: '234-567-8901',
    memberRegisterDate: '',
    memberRegisterStatus: false,
  },
  {
    id: 3,
    memberEmail: 'john.smith@flowbite.com',
    memberName: 'John Smith',
    memberPhone: '345-678-9012',
    memberRegisterDate: '2022-03-10',
    memberRegisterStatus: true,
  },
  {
    id: 4,
    memberEmail: 'emily.jones@flowbite.com',
    memberName: 'Emily Jones',
    memberPhone: '456-789-0123',
    memberRegisterDate: '',
    memberRegisterStatus: false,
  },
  {
    id: 5,
    memberEmail: 'michael.brown@flowbite.com',
    memberName: 'Michael Brown',
    memberPhone: '567-890-1234',
    memberRegisterDate: '',
    memberRegisterStatus: false,
  },
  {
    id: 6,
    memberEmail: 'lisa.wilson@flowbite.com',
    memberName: 'Lisa Wilson',
    memberPhone: '678-901-2345',
    memberRegisterDate: '2022-06-15',
    memberRegisterStatus: true,
  },
  {
    id: 7,
    memberEmail: 'david.taylor@flowbite.com',
    memberName: 'David Taylor',
    memberPhone: '789-012-3456',
    memberRegisterDate: '2022-07-10',
    memberRegisterStatus: true,
  },
  {
    id: 8,
    memberEmail: 'david.taylor@flowbite.com',
    memberName: 'David Taylor',
    memberPhone: '789-012-3456',
    memberRegisterDate: '2022-07-10',
    memberRegisterStatus: true,
  },
];
