export const users = [
  {
    id: 1,
    memberEmail: '',
    memberName: '',
    memberPhone: '',
    createdAt: '',
    pending: true,
  },
  {
    id: 2,
    memberEmail: '',
    memberName: '',
    memberPhone: '',
    createdAt: '',
    pending: false,
  },
  {
    id: 3,
    memberEmail: '',
    memberName: '',
    memberPhone: '',
    createdAt: '',
    pending: true,
  },
  {
    id: 4,
    memberEmail: '',
    memberName: '',
    memberPhone: '',
    createdAt: '',
    pending: false,
  },
  {
    id: 5,
    memberEmail: '',
    memberName: '',
    memberPhone: '',
    createdAt: '',
    pending: false,
  },
  {
    id: 6,
    memberEmail: '',
    memberName: '',
    memberPhone: '',
    createdAt: '',
    pending: true,
  },
  {
    id: 7,
    memberEmail: '',
    memberName: '',
    memberPhone: '',
    createdAt: '',
    pending: true,
  },
  {
    id: 8,
    memberEmail: '',
    memberName: '',
    memberPhone: '',
    createdAt: '',
    pending: true,
  },
];
