export const product = [
  {
    id: 1,
    productName: '상품1',
    stockQuantity: '10',
    productPrice: '10000',
    productDiscount: '10',
    productStatus: true,
    orderOption: 'SUBSCRIPTION',
  },
  {
    id: 2,
    productName: '상품2',
    stockQuantity: '20',
    productPrice: '20000',
    productDiscount: '15',
    productStatus: true,
    orderOption: 'SINGLE',
  },
  {
    id: 3,
    productName: '상품3',
    stockQuantity: '30',
    productPrice: '30000',
    productDiscount: '20',
    productStatus: false,
    orderOption: 'SUBSCRIPTION',
  },
  {
    id: 4,
    productName: '상품4',
    stockQuantity: '40',
    productPrice: '40000',
    productDiscount: '25',
    productStatus: true,
    orderOption: 'SINGLE',
  },
  {
    id: 5,
    productName: '상품5',
    stockQuantity: '50',
    productPrice: '50000',
    productDiscount: '30',
    productStatus: true,
    orderOption: 'SUBSCRIPTION',
  },
  {
    id: 6,
    productName: '상품6',
    stockQuantity: '60',
    productPrice: '60000',
    productDiscount: '35',
    productStatus: false,
    orderOption: 'SINGLE',
  },
  {
    id: 7,
    productName: '상품7',
    stockQuantity: '70',
    productPrice: '70000',
    productDiscount: '40',
    productStatus: true,
    orderOption: 'SUBSCRIPTION',
  },
  {
    id: 8,
    productName: '상품8',
    stockQuantity: '80',
    productPrice: '80000',
    productDiscount: '45',
    productStatus: false,
    orderOption: 'SINGLE',
  },
  {
    id: 9,
    productName: '상품9',
    stockQuantity: '90',
    productPrice: '90000',
    productDiscount: '50',
    productStatus: true,
    orderOption: 'SUBSCRIPTION',
  },
  {
    id: 10,
    productName: '상품10',
    stockQuantity: '100',
    productPrice: '100000',
    productDiscount: '55',
    productStatus: true,
    orderOption: 'SINGLE',
  },
];
