export const payments = {
  accounts: [
    {
      id: 1,
      name: '홍길동',
      email: 'owen123@naver.com',
      method: '계좌',
      company: '우리은행',
      paymentNumber: '21-****-****-41',
    },
    {
      id: 2,
      name: '홍길동',
      email: 'owen123@naver.com',
      method: '계좌',
      company: '우리은행',
      paymentNumber: '21-****-****-41',
    },
    {
      id: 3,
      name: '홍길동',
      email: 'owen123@naver.com',
      method: '계좌',
      company: '우리은행',
      paymentNumber: '21-****-****-41',
    },
    {
      id: 4,
      name: '홍길동',
      email: 'owen123@naver.com',
      method: '계좌',
      company: '우리은행',
      paymentNumber: '21-****-****-41',
    },
    {
      id: 5,
      name: '홍길동',
      email: 'owen123@naver.com',
      method: '계좌',
      company: '우리은행',
      paymentNumber: '21-****-****-41',
    },
    {
      id: 6,
      name: '홍길동',
      email: 'owen123@naver.com',
      method: '계좌',
      company: '우리은행',
      paymentNumber: '21-****-****-41',
    },
    {
      id: 7,
      name: '홍길동',
      email: 'owen123@naver.com',
      method: '계좌',
      company: '우리은행',
      paymentNumber: '21-****-****-41',
    },
    {
      id: 8,
      name: '홍길동',
      email: 'owen123@naver.com',
      method: '계좌',
      company: '우리은행',
      paymentNumber: '21-****-****-41',
    },
    {
      id: 9,
      name: '홍길동',
      email: 'owen123@naver.com',
      method: '계좌',
      company: '우리은행',
      paymentNumber: '21-****-****-41',
    },
    {
      id: 10,
      name: '홍길동10',
      email: 'owen123@naver.com',
      method: '계좌',
      company: '우리은행',
      paymentNumber: '21-****-****-41',
    },
  ],
  cards: [
    {
      id: 1,
      name: '홍길동',
      email: 'owen123@naver.com',
      method: '카드',
      company: '국민카드',
      paymentNumber: '21-****-****-41',
    },
    {
      id: 2,
      name: '강길동',
      email: 'owen123@naver.com',
      method: '카드',
      company: '국민카드',
      paymentNumber: '21-****-****-41',
    },
    {
      id: 3,
      name: '김길동',
      email: 'owen123@naver.com',
      method: '카드',
      company: '국민카드',
      paymentNumber: '21-****-****-41',
    },
    {
      id: 4,
      name: '강감찬',
      email: 'owen123@naver.com',
      method: '카드',
      company: '국민카드',
      paymentNumber: '21-****-****-41',
    },
    {
      id: 5,
      name: '이순신',
      email: 'owen123@naver.com',
      method: '카드',
      company: '국민카드',
      paymentNumber: '21-****-****-41',
    },
    {
      id: 6,
      name: '을지문덕',
      email: 'owen123@naver.com',
      method: '카드',
      company: '국민카드',
      paymentNumber: '21-****-****-41',
    },
    {
      id: 7,
      name: '양만춘',
      email: 'owen123@naver.com',
      method: '카드',
      company: '국민카드',
      paymentNumber: '21-****-****-41',
    },
    {
      id: 8,
      name: '분홍콩',
      email: 'owen123@naver.com',
      method: '카드',
      company: '국민카드',
      paymentNumber: '21-****-****-41',
    },
    {
      id: 9,
      name: '이맹구',
      email: 'owen123@naver.com',
      method: '카드',
      company: '국민카드',
      paymentNumber: '21-****-****-41',
    },
    {
      id: 10,
      name: '아맹콩',
      email: 'owen123@naver.com',
      method: '카드',
      company: '국민카드',
      paymentNumber: '21-****-****-41',
    },
  ],
};
