export const payments = [
  {
    id: 1,
    name: '홍길동',
    email: 'owen123@naver.com',
    method: '계좌',
    bank: '우리은행',
    accountNumber: '21-****-****-41',
  },
  {
    id: 2,
    name: '홍길동',
    email: 'owen123@naver.com',
    method: '계좌',
    bank: '우리은행',
    accountNumber: '21-****-****-41',
  },
  {
    id: 3,
    name: '홍길동',
    email: 'owen123@naver.com',
    method: '계좌',
    bank: '우리은행',
    accountNumber: '21-****-****-41',
  },
  {
    id: 4,
    name: '홍길동',
    email: 'owen123@naver.com',
    method: '계좌',
    bank: '우리은행',
    accountNumber: '21-****-****-41',
  },
  {
    id: 5,
    name: '홍길동',
    email: 'owen123@naver.com',
    method: '계좌',
    bank: '우리은행',
    accountNumber: '21-****-****-41',
  },
  {
    id: 6,
    name: '홍길동',
    email: 'owen123@naver.com',
    method: '계좌',
    bank: '우리은행',
    accountNumber: '21-****-****-41',
  },
  {
    id: 7,
    name: '홍길동',
    email: 'owen123@naver.com',
    method: '계좌',
    bank: '우리은행',
    accountNumber: '21-****-****-41',
  },
  {
    id: 8,
    name: '홍길동',
    email: 'owen123@naver.com',
    method: '계좌',
    bank: '우리은행',
    accountNumber: '21-****-****-41',
  },
  {
    id: 9,
    name: '홍길동',
    email: 'owen123@naver.com',
    method: '계좌',
    bank: '우리은행',
    accountNumber: '21-****-****-41',
  },
  {
    id: 10,
    name: '홍길동',
    email: 'owen123@naver.com',
    method: '계좌',
    bank: '우리은행',
    accountNumber: '21-****-****-41',
  },
];
