name: Backend CD with Gradle
on:
  push:
    branches:
      - main
    paths:
      - 'ubun2_be/**'
  
permissions:
  contents: read
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: "temurin"
      - name: Make application.properties
        run: |
          cd ./ubun2_be/src/main/resources
          touch ./application.properties
          echo "${{ secrets.PROPERTIES }}" > ./application.properties
        shell: bash
      - name: Build with Gradle
        run: |
          cd ./ubun2_be
          chmod +x ./gradlew
          ./gradlew clean build -x test
  deploy-to-Server:
    if: github.event_name == 'push'
    name: Deploy
    runs-on: ubuntu-latest
    needs: build-test
    steps:
      - uses: actions/checkout@v3
      - name: Docker build & push to prod
        run: |
          cd ./ubun2_be
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker buildx build --push --platform linux/amd64 -t ${{ secrets.DOCKER_BACK_REPO }} .
          
      - name: Deploy start
        uses: appleboy/ssh-action@master
        id: deploy
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_KEY }}
          port: ${{ secrets.EC2_SSH_PORT }}
          
          script: |
            sudo docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            sudo docker pull ${{ secrets.DOCKER_BACK_REPO }}
            docker-compose up -d ubun2_be
