name: Frontend CD with Node.js
on:
  push:
    branches:
      - main
    paths:
      - 'ubun2_fe/**'
  
permissions:
  contents: read
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.12.0'
      - name: Create .env file
        run: |
          cd ./ubun2_fe
          echo "${{ secrets.FRONT_ENV }}" > .env
      - name: Install dependencies
        run: |
          cd ./ubun2_fe
          npm ci
          npm run build
  deploy-to-Server:
    if: github.event_name == 'push'
    name: Deploy
    runs-on: ubuntu-latest
    needs: build-test
    steps:
      - uses: actions/checkout@v3
      - name: Create .env file
        run: |
          cd ./ubun2_fe
          echo "${{ secrets.FRONT_ENV }}" > .env
      - name: Docker build & push to prod
        run: |
          cd ./ubun2_fe
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker buildx build --push --platform linux/amd64 -t ${{ secrets.DOCKER_FRONT_REPO }} .
          
      - name: Deploy start
        uses: appleboy/ssh-action@master
        id: deploy
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_KEY }}
          port: ${{ secrets.EC2_SSH_PORT }}
          
          script: |
            sudo docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            sudo docker pull ${{ secrets.DOCKER_FRONT_REPO }}
            docker-compose up -d ubun2_fe
