export const addresses = [
  {
    id: 1,
    name: '홍길동',
    email: 'owen123@naver.com',
    city: '서울특별시',
    town: '중구',
    detail: '창경궁로 254 403호',
  },
  {
    id: 2,
    name: '김길동',
    email: 'candy1223@naver.com',
    city: '서울특별시',
    town: '중구',
    detail: '창경궁로 254 403호',
  },
  {
    id: 3,
    name: '이순신',
    email: 'paperkpo@naver.com',
    city: '서울특별시',
    town: '중구',
    detail: '창경궁로 254 402호',
  },
  {
    id: 4,
    name: '이순신',
    email: 'leesoonshin@naver.com',
    city: '서울특별시',
    town: '중구',
    detail: '창경궁로 254 402호',
  },
  {
    id: 5,
    name: '이순신',
    email: 'leesoonshin@naver.com',
    city: '서울특별시',
    town: '중구',
    detail: '창경궁로 254 402호',
  },
  {
    id: 6,
    name: '을지문덕',
    email: 'leesoonshin@naver.com',
    city: '서울특별시',
    town: '중구',
    detail: '창경궁로 254 402호',
  },
  {
    id: 7,
    name: '장보고',
    email: 'leesoonshin@naver.com',
    city: '서울특별시',
    town: '중구',
    detail: '창경궁로 254 402호',
  },
  {
    id: 8,
    name: '양만춘',
    email: 'leesoonshin@naver.com',
    city: '서울특별시',
    town: '중구',
    detail: '창경궁로 254 402호',
  },
  {
    id: 9,
    name: '대조영',
    email: 'leesoonshin@naver.com',
    city: '서울특별시',
    town: '중구',
    detail: '창경궁로 254 402호',
  },
  {
    id: 10,
    name: '강감찬',
    email: 'leesoonshin@naver.com',
    city: '서울특별시',
    town: '중구',
    detail: '창경궁로 254 402호',
  },
];
